--Acciones de referencia--
ALTER TABLE SolicitudesDeServicios DROP CONSTRAINT FK_SDS_SOLICITUDES;
ALTER TABLE Citas DROP CONSTRAINT FK_CITAS_SOLICITUDES;

ALTER TABLE SolicitudesDeServicios ADD CONSTRAINT FK_SDS_SOLICITUDES
  FOREIGN KEY (solicitud) REFERENCES Solicitudes(IDsolicitud)
  ON DELETE CASCADE;

ALTER TABLE Citas ADD CONSTRAINT FK_CITAS_SOLICITUDES
  FOREIGN KEY (solicitud) REFERENCES Solicitudes(IDsolicitud)
  ON DELETE CASCADE;