-------GRANT-----------
GRANT SELECT TO VETERINARIO;
GRANT SELECT TO DUEÑO;
GRANT ALL TO ADMINISTRADOR;
GRANT PA_DUEÑO_VETERINARIA TO DUEÑO_CLINICA;

--------------GRANT USER--------
GRANT DUEÑO_CLINICA TO Martin;
GRANT CAJERO TO Daniela;
GRANT ADMINISTRADOR TO SebasF;
GRANT ADMINISTRADOR TO SebasG;
GRANT DUEÑO TO Felipe;
GRANT VETERINARIO TO Luis;