----------ROLES------------------
CREATE ROLE DUEÑO;
CREATE ROLE DUEÑO_CLINICA;

CREATE ROLE CAJERO
  IDENTIFIED BY cajero001;
CREATE ROLE VETERINARIO
  IDENTIFIED BY vete001;
CREATE ROLE ADMINISTRADOR
  IDENTIFIED BY adminclinica;

-----------USERS------------
CREATE USER SebasF
  IDENTIFIED BY sebastianfrasic368;
CREATE USER SebasG
  IDENTIFIED BY srgomez2018;
CREATE USER Daniela
  IDENTIFIED BY angiedruiz;
CREATE USER Martin
  IDENTIFIED BY pyro1999;
CREATE USER Felipe
  IDENTIFIED BY jujus2009;
CREATE USER Luis
  IDENTIFIED BY luisg1991;