--Primarias--

ALTER TABLE Personas ADD CONSTRAINT PK_PERSONAS PRIMARY KEY (cedula);
ALTER TABLE Empleados ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (cedula);
ALTER TABLE Veterinarios ADD CONSTRAINT PK_VETERINARIOS PRIMARY KEY (cedula);
ALTER TABLE Asistentes ADD CONSTRAINT PK_ASISTENTES PRIMARY KEY (cedula);
ALTER TABLE Cajeros ADD CONSTRAINT PK_CAJEROS PRIMARY KEY (cedula);
ALTER TABLE Dueños ADD CONSTRAINT PK_DUEÑOS PRIMARY KEY (cedula);
ALTER TABLE Mascotas ADD CONSTRAINT PK_MASCOTAS PRIMARY KEY (IDmascota);
ALTER TABLE Citas ADD CONSTRAINT PK_CITAS PRIMARY KEY (solicitud);
ALTER TABLE Solicitudes ADD CONSTRAINT PK_SOLICITUDES PRIMARY KEY (IDsolicitud);
ALTER TABLE SolicitudesDeServicios ADD CONSTRAINT PK_SOLICITUDESDESERVICIOS PRIMARY KEY (solicitud, servicio);
ALTER TABLE Servicios ADD CONSTRAINT PK_SERVICIOS PRIMARY KEY (nombreServicio);
ALTER TABLE PrestacionesServicios ADD CONSTRAINT PK_PRESTACIONESSERVICIOS PRIMARY KEY (cita);
