--xIndices--
DROP INDEX INDX_MASCOTAS;
DROP INDEX INDX_MASCOTAS2;
DROP INDEX INDX_PERSONAS;

-- xVistas--
DROP VIEW CITAS_ATENTIDAS;
DROP VIEW OBSERV_SERVICIOS;
DROP VIEW DINERO_INVERTIDO;
DROP VIEW INFO_MASCOTAS;