--xForaneas--
ALTER TABLE Empleados DROP CONSTRAINT FK_EMPLEADOS_PERSONAS;
ALTER TABLE Veterinarios DROP CONSTRAINT FK_VETERINARIOS_EMPLEADOS;
ALTER TABLE Asistentes DROP CONSTRAINT FK_ASISTENTES_EMPLEADOS;
ALTER TABLE Cajeros DROP CONSTRAINT FK_CAJEROS_EMPLEADOS;
ALTER TABLE Dueños DROP CONSTRAINT FK_DUEÑOS_PERSONAS;
ALTER TABLE Mascotas DROP CONSTRAINT FK_MASCOTAS_DUEÑOS;
ALTER TABLE Citas DROP CONSTRAINT FK_CITAS_EMPLEADOS;
ALTER TABLE Citas DROP CONSTRAINT FK_CITAS_SOLICITUDES;
ALTER TABLE Solicitudes DROP CONSTRAINT FK_SOLICITUDES_CAJEROS;
ALTER TABLE Solicitudes DROP CONSTRAINT FK_SOLICITUDES_DUEÑOS;
ALTER TABLE Solicitudes DROP CONSTRAINT FK_SOLICITUDES_MASCOTAS;
ALTER TABLE SolicitudesDeServicios DROP CONSTRAINT FK_SDS_SOLICITUDES;
ALTER TABLE SolicitudesDeServicios DROP CONSTRAINT FK_SDS_SERVICIOS;
ALTER TABLE PrestacionesServicios DROP CONSTRAINT FK_PDS_CITAS;

--xUnicas--
ALTER TABLE Personas DROP CONSTRAINT UK_PERSONAS;

--xPrimarias--
ALTER TABLE Personas DROP CONSTRAINT PK_PERSONAS;
ALTER TABLE Empleados DROP CONSTRAINT PK_EMPLEADOS;
ALTER TABLE Veterinarios DROP CONSTRAINT PK_VETERINARIOS;
ALTER TABLE Asistentes DROP CONSTRAINT PK_ASISTENTES;
ALTER TABLE Cajeros DROP CONSTRAINT PK_CAJEROS;
ALTER TABLE Dueños DROP CONSTRAINT PK_DUEÑOS;
ALTER TABLE Mascotas DROP CONSTRAINT PK_MASCOTAS;
ALTER TABLE Citas DROP CONSTRAINT PK_CITAS;
ALTER TABLE Solicitudes DROP CONSTRAINT PK_SOLICITUDES;
ALTER TABLE SolicitudesDeServicios DROP CONSTRAINT PK_SOLICITUDESDESERVICIOS;
ALTER TABLE Servicios DROP CONSTRAINT PK_SERVICIOS;
ALTER TABLE PrestacionesServicios DROP CONSTRAINT PK_PRESTACIONESSERVICIOS;

--xTablas--

DROP TABLE Personas;
DROP TABLE Empleados;
DROP TABLE Veterinarios;
DROP TABLE Asistentes;
DROP TABLE Cajeros;
DROP TABLE Dueños;
DROP TABLE Mascotas;
DROP TABLE Citas;
DROP TABLE Solicitudes;
DROP TABLE SolicitudesDeServicios;
DROP TABLE Servicios;
DROP TABLE PrestacionesServicios;